
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace demo
{

using System;
    using System.Collections.Generic;
    
public partial class Clients
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Clients()
    {

        this.Orders = new HashSet<Orders>();

    }


    public int Client_code { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public Nullable<int> Passport_series { get; set; }

    public Nullable<int> Passport_number { get; set; }

    public Nullable<System.DateTime> Birthday_date { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Orders> Orders { get; set; }

}

}
